AzisabaNetwork/RyuZUPluginChat

pom.xml
src/main/java/ryuzupluginchat/ryuzupluginchat/RyuZUPluginChat.java
src/main/java/ryuzupluginchat/ryuzupluginchat/command/VCCommand.java
src/main/java/ryuzupluginchat/ryuzupluginchat/config/RPCConfig.java
src/main/java/ryuzupluginchat/ryuzupluginchat/discord/DiscordHandler.java
src/main/java/ryuzupluginchat/ryuzupluginchat/listener/ChatListener.java
src/main/java/ryuzupluginchat/ryuzupluginchat/message/MessageDataFactory.java
src/main/java/ryuzupluginchat/ryuzupluginchat/message/data/ChannelChatMessageData.java
src/main/java/ryuzupluginchat/ryuzupluginchat/redis/VCLunaChatChannelSharer.java
src/main/resources/config.yml
src/main/resources/plugin.yml

#12 より
* Configに設定項目を追加
* voicechat chの内容をDiscordに転送
* Discordの内容をvoicechat chに転送
* /vc 実装
* 荒らし対策のためクールタイム追加
* 荒らし対策のためメンション除外 ( @ を全角に変更 )
* Discordのメッセージをすぐに編集して送信者を表示

Discordとの連携機能を追加

---

pom.xml

LunaChatをprovidedに変更

---

pom.xml
src/main/java/ryuzupluginchat/ryuzupluginchat/RyuZUPluginChat.java
src/main/java/ryuzupluginchat/ryuzupluginchat/config/RPCConfig.java
src/main/java/ryuzupluginchat/ryuzupluginchat/discord/DiscordHandler.java
src/main/java/ryuzupluginchat/ryuzupluginchat/discord/DiscordMessageConnection.java
src/main/java/ryuzupluginchat/ryuzupluginchat/discord/data/ChannelChatSyncData.java
src/main/java/ryuzupluginchat/ryuzupluginchat/discord/data/ChatSyncData.java
src/main/java/ryuzupluginchat/ryuzupluginchat/discord/data/GlobalChatSyncData.java
src/main/java/ryuzupluginchat/ryuzupluginchat/discord/data/PrivateChatSyncData.java
src/main/java/ryuzupluginchat/ryuzupluginchat/redis/PlayerUUIDMapContainer.java
src/main/resources/config.yml

ConfigのDiscord欄のフォーマットを一新し、好きなDiscordチャンネルと好きな範囲のマイクラチャットを接続できるように

Discordの接続チャンネルを細かく設定できるように変更

---

pom.xml
src/main/java/ryuzupluginchat/ryuzupluginchat/RyuZUPluginChat.java
src/main/java/ryuzupluginchat/ryuzupluginchat/command/HideCommand.java
src/main/java/ryuzupluginchat/ryuzupluginchat/command/RPCCommand.java
src/main/java/ryuzupluginchat/ryuzupluginchat/command/UnHideCommand.java
src/main/java/ryuzupluginchat/ryuzupluginchat/listener/LunaChatHideCommandListener.java
src/main/java/ryuzupluginchat/ryuzupluginchat/message/MessageProcessor.java
src/main/java/ryuzupluginchat/ryuzupluginchat/redis/HideInfoController.java
src/main/resources/plugin.yml

* /hide /unhide コマンドを追加
* /ch hide コマンドを実行したときに /hide コマンドへ促す機能を追加

他のプレイヤーのチャットを非表示にできる機能を追加

---

pom.xml
src/main/java/ryuzupluginchat/ryuzupluginchat/config/RPCConfig.java
src/main/resources/config.yml

`server-name` だけ `serverName` になっていたので

Configをダッシュケースに統一

---

pom.xml
src/main/java/ryuzupluginchat/ryuzupluginchat/listener/OutdatedCommandCaptureListener.java

* /tell でもRPCのTabCompleteが動作するように修正

TabCompleteの乗っ取り

---

pom.xml
src/main/java/ryuzupluginchat/ryuzupluginchat/command/TellCommand.java

先頭の文字が一致するプレイヤーが1人の場合はそのプレイヤーにtellを送る機能を追加

Tellの送信先解決改善

---

pom.xml
src/main/java/ryuzupluginchat/ryuzupluginchat/message/MessageProcessor.java

運営は全プレイヤーの個人チャットを見ることが出来るように設定

運営が個人チャットを見れる機能

---

src/main/java/ryuzupluginchat/ryuzupluginchat/message/MessageDataFactory.java
src/main/java/ryuzupluginchat/ryuzupluginchat/message/data/ChannelChatMessageData.java
src/main/java/ryuzupluginchat/ryuzupluginchat/message/data/GlobalMessageData.java
src/main/java/ryuzupluginchat/ryuzupluginchat/message/data/PrivateMessageData.java
src/main/java/ryuzupluginchat/ryuzupluginchat/util/ColorUtils.java
src/main/java/ryuzupluginchat/ryuzupluginchat/util/LuckPermsPrefixSuffixUtils.java

Rename useful to util

---

pom.xml
src/main/java/ryuzupluginchat/ryuzupluginchat/RyuZUPluginChat.java
src/main/java/ryuzupluginchat/ryuzupluginchat/redis/HideInfoController.java
src/main/java/ryuzupluginchat/ryuzupluginchat/redis/MessagePublisher.java
src/main/java/ryuzupluginchat/ryuzupluginchat/redis/MessageSubscriber.java
src/main/java/ryuzupluginchat/ryuzupluginchat/redis/PlayerUUIDMapContainer.java
src/main/java/ryuzupluginchat/ryuzupluginchat/redis/PrivateChatIDGetter.java
src/main/java/ryuzupluginchat/ryuzupluginchat/redis/PrivateChatReachedSubscriber.java
src/main/java/ryuzupluginchat/ryuzupluginchat/redis/ReplyTargetFetcher.java
src/main/java/ryuzupluginchat/ryuzupluginchat/redis/RyuZUPrefixSuffixContainer.java
src/main/java/ryuzupluginchat/ryuzupluginchat/redis/VCLunaChatChannelSharer.java
src/main/java/ryuzupluginchat/ryuzupluginchat/util/JedisUtils.java

* RedisPoolを使用してマルチスレッドでの処理が衝突しないように修正
* Redisに再接続する機能を追加

Redisの接続関係の処理を最適化

---

pom.xml
src/main/java/ryuzupluginchat/ryuzupluginchat/listener/ChatListener.java
src/main/java/ryuzupluginchat/ryuzupluginchat/message/MessageDataFactory.java

先頭に `#` を付けても日本語化が解除されないバグを修正

---

pom.xml
src/main/java/ryuzupluginchat/ryuzupluginchat/message/data/ChannelChatMessageData.java

LunaChatフォーマットを追加

---

src/main/java/ryuzupluginchat/ryuzupluginchat/listener/JoinQuitListener.java

とりあえず #59 の原因が分からないので 参加/退出 の処理をBukkitの非同期処理に変えて固まらないようにしてみた

🚧 [Working in Progress] #59 の対策

---

pom.xml
src/main/java/ryuzupluginchat/ryuzupluginchat/redis/PrivateChatReachedSubscriber.java

[HotFix] /tell が動かないバグを修正

---

pom.xml
src/main/java/ryuzupluginchat/ryuzupluginchat/command/ReplyCommand.java
src/main/java/ryuzupluginchat/ryuzupluginchat/command/TellCommand.java

* /tell の処理を非同期化
* /reply の処理を非同期化

:rocket: /tellと/replyの処理を非同期化

---

pom.xml
src/main/java/net/azisaba/ryuzupluginchat/RyuZUPluginChat.java
src/main/java/net/azisaba/ryuzupluginchat/updater/GitHubPluginUpdater.java
src/main/java/net/azisaba/ryuzupluginchat/updater/UpdateStatus.java

:sparkles: 自動アップデート機能を追加

---

pom.xml
src/main/java/net/azisaba/ryuzupluginchat/redis/HideInfoController.java

* 誰かがプレイヤーを /hide したのち、そのプレイヤーを全員が /unhide すると Redis のValueが空白となり、更新時にエラーとなるバグを修正

:bug: DBから/hide情報のデータを更新しようとするとエラーになることがあるバグを修正

---

pom.xml
src/main/java/net/azisaba/ryuzupluginchat/RyuZUPluginChat.java
src/main/java/net/azisaba/ryuzupluginchat/taskchain/BukkitTaskChainFactory.java

* 60秒だとアジ鯖のDockerのタイムアウトと被る上にPaperの強制シャットダウンまでのタイムアウトとも被るので30秒に短縮

:zap: TaskChainのタイムアウトを30秒に短縮

---

src/main/java/net/azisaba/ryuzupluginchat/RyuZUPluginChat.java
src/main/java/net/azisaba/ryuzupluginchat/command/HideListCommand.java
src/main/java/net/azisaba/ryuzupluginchat/redis/HideInfoController.java
src/main/resources/plugin.yml

Add /hidelist

---

src/main/java/net/azisaba/ryuzupluginchat/message/MessageProcessor.java

Log warning if senderUUID of player is null

---

src/main/java/net/azisaba/ryuzupluginchat/message/MessageDataFactory.java
src/main/java/net/azisaba/ryuzupluginchat/message/MessageProcessor.java
src/main/java/net/azisaba/ryuzupluginchat/message/data/ChannelChatMessageData.java
src/main/java/net/azisaba/ryuzupluginchat/message/data/GlobalMessageData.java
src/main/java/net/azisaba/ryuzupluginchat/message/data/PrivateMessageData.java

:bug::boom: ログイン直後のプレイヤーに/hideが適用されないバグを修正

---

src/main/java/net/azisaba/ryuzupluginchat/event/AsyncChannelMessageEvent.java
src/main/java/net/azisaba/ryuzupluginchat/event/AsyncGlobalMessageEvent.java
src/main/java/net/azisaba/ryuzupluginchat/event/AsyncMessageEvent.java
src/main/java/net/azisaba/ryuzupluginchat/event/AsyncPrivateMessageEvent.java
src/main/java/net/azisaba/ryuzupluginchat/message/MessageProcessor.java
src/main/java/net/azisaba/ryuzupluginchat/message/data/ChannelChatMessageData.java
src/main/java/net/azisaba/ryuzupluginchat/message/data/GlobalMessageData.java
src/main/java/net/azisaba/ryuzupluginchat/message/data/MessageData.java
src/main/java/net/azisaba/ryuzupluginchat/message/data/PrivateMessageData.java
src/main/java/net/azisaba/ryuzupluginchat/message/data/SystemMessageData.java

```java
@EventHandler
public void onGlobalMessage(AsyncGlobalMessageEvent e) {
getLogger().info("AsyncGlobalMessageEvent: Message: " + e.getMessage() + ", Recipients: " + e.getRecipients());
}
@EventHandler
public void onChannelMessage(AsyncChannelMessageEvent e) {
getLogger().info("AsyncChannelMessageEvent: Message: " + e.getMessage() + ", Recipients: " + e.getRecipients());
}
@EventHandler
public void onPrivateMessage(AsyncPrivateMessageEvent e) {
getLogger().info("AsyncPrivateMessageEvent: Message: " + e.getMessage() + ", Recipients: " + e.getRecipients());
}
```
上のコードで軽いテストしたけどだいたいちゃんと動く
[rpc.txt](https://github.com/AzisabaNetwork/RyuZUPluginChat/files/9481851/rpc.txt)

✨ Add Async(Global|Channel|Private)MessageEvent

---

src/main/java/net/azisaba/ryuzupluginchat/RyuZUPluginChat.java
src/main/java/net/azisaba/ryuzupluginchat/command/HideAllCommand.java
src/main/java/net/azisaba/ryuzupluginchat/listener/HideAllListener.java
src/main/java/net/azisaba/ryuzupluginchat/listener/JoinQuitListener.java
src/main/java/net/azisaba/ryuzupluginchat/redis/HideAllInfoController.java
src/main/resources/plugin.yml

:sparkles: /hideallコマンドを実装

---

src/main/java/net/azisaba/ryuzupluginchat/message/MessageDataFactory.java
src/main/java/net/azisaba/ryuzupluginchat/message/MessageProcessor.java
src/main/java/net/azisaba/ryuzupluginchat/message/data/PrivateMessageData.java
src/main/java/net/azisaba/ryuzupluginchat/redis/MessagePublisher.java
src/main/java/net/azisaba/ryuzupluginchat/redis/PrivateChatReachedSubscriber.java
src/main/java/net/azisaba/ryuzupluginchat/redis/PrivateChatResponseWaiter.java

:sparkles: 個人チャットにDisplayNameを実装

---

src/main/java/net/azisaba/ryuzupluginchat/RyuZUPluginChat.java
src/main/java/net/azisaba/ryuzupluginchat/listener/PrivateChatDebugListener.java
src/main/java/net/azisaba/ryuzupluginchat/message/MessageProcessor.java
src/main/java/net/azisaba/ryuzupluginchat/redis/PrivateChatResponseWaiter.java
src/main/java/net/azisaba/ryuzupluginchat/util/TaskSchedulingUtils.java

:lock: 個人チャットが権限のない第三者に見えるバグの修正

---

pom.xml
src/main/java/net/azisaba/ryuzupluginchat/RyuZUPluginChat.java
src/main/java/net/azisaba/ryuzupluginchat/command/HideCommand.java
src/main/java/net/azisaba/ryuzupluginchat/command/HideListCommand.java
src/main/java/net/azisaba/ryuzupluginchat/command/RPCCommand.java
src/main/java/net/azisaba/ryuzupluginchat/command/UnHideCommand.java
src/main/java/net/azisaba/ryuzupluginchat/command/VCCommand.java
src/main/java/net/azisaba/ryuzupluginchat/config/RPCConfig.java
src/main/java/net/azisaba/ryuzupluginchat/discord/deliverer/DiscordMessageDeliverer.java
src/main/java/net/azisaba/ryuzupluginchat/listener/OutdatedCommandCaptureListener.java
src/main/java/net/azisaba/ryuzupluginchat/redis/HideInfoController.java

起動はできる。global/channel/privateチャットが使えることも確認済み

コードをキレイキレイ＆バージョンを3.1.0に更新

---

src/main/java/net/azisaba/ryuzupluginchat/RyuZUPluginChat.java
src/main/java/net/azisaba/ryuzupluginchat/config/RPCConfig.java
src/main/resources/config.yml

[✨ Redisのユーザー名指定に対応](https://github.com/AzisabaNetwork/RyuZUPluginChat/pull/125/commits/30b41d693dd8f9f1c56416e55780c1660e1caf16)
[🐛 PINGが制限されている場合チャットできなくなるバグを修正](https://github.com/AzisabaNetwork/RyuZUPluginChat/pull/125/commits/3360be52c440ae03db7016a3db53aa4f4bee7da0)

:sparkles: Redisのユーザー機能に対応

---

src/main/java/net/azisaba/ryuzupluginchat/message/MessageProcessor.java
src/main/java/net/azisaba/ryuzupluginchat/redis/MessageSubscriber.java
src/main/java/net/azisaba/ryuzupluginchat/redis/PrivateChatResponseWaiter.java
src/main/java/net/azisaba/ryuzupluginchat/redis/ReachedPrivateChatData.java

:bug: 個人チャットが見えなかったり重複して表示されるバグを修正

---

.github/workflows/deploy.yml
pom.xml

it worked in LunaChatPlus so it should work too

Add deploy configuration

---

pom.xml
src/main/java/net/azisaba/ryuzupluginchat/redis/PrivateChatResponseWaiter.java

ついでにrelocationの設定ミスで起動できないバグも修正

:bug: /rpc reloadで個人チャットが重複するバグを修正
